window.jsonFinancerMaster = [
	'State Bank Of India',
	'HDFC Ltd.',
	'ICICI Bank',
	'AXIS Bank',
	'LIC Housing Finance',
	'ICICI Home Finance',
	'Aditya Birla Housing Finance',
	'Bajaj Housing Finance',
	'Reliance Home Finance',
	'PNB Housing Finance',
	'Indiabulls Housing Finance',
	'Aavas Financiers Ltd.',
	'Au Housing Finance Ltd.',
	'Home First Finance Company India Ltd. (HFFC)',
	'GRUH Housing Finance',
	'Magma Housing Finance',
	'Dewan Housing Finance Corporation (DHFL)',
	'Aadhar Housing Finance Ltd.',
];